plugins {
    id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'Project_01_Chat'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

sourceSets {
    main {
        java {
            srcDirs = ['ChatServer/src', 'ChatClient/src', 'src/main/java']
        }
    }
}
